POST http://127.0.0.1:8000/users/
Content-Type: application/json

{
"first_name": "Nico",
"last_name": "Jöch",
"email": "nico@nicodn.com",
"username": "nicoJoech",
"password": "nico"
}

###

GET http://127.0.0.1:8000/users/
Accept: application/json

###

GET http://127.0.0.1:8000/test
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJuaWNvIiwiZXhwIjoxNzAxNzExNTU1fQ.6_aAeb7ROw9h6Wr9QIG9LkwMQSx1jhcy7BIwAgSTxkM

###

GET http://127.0.0.1:8000/test
Accept: application/json

###

DELETE http://127.0.0.1:8000/users/1

###
POST http://127.0.0.1:8000/agents/
Content-Type: application/json

{
  "name": "TestCrawler",
  "min_area": 75.5,
  "max_price": 120000.0,
  "number_of_rooms": 2,
  "zip_code": "54321",
  "state": "New York",
  "rent": true,
  "type": "Commercial"
}

###
DELETE http://127.0.0.1:8000/agents/1